### ISSUE TITLE
Load conditionally

### ISSUE THREAD

**Issue by ghost** [mattia72/vim-delphi#2]
Does the plugin load conditionally just for delphi and pascal files or do I have to write something like:
 `Plug 'mattia72/vim-delphi', { 'for': ['delphi', 'pascal'] }`

**Comment by mattia72** [comment]
This is a filetype plugin, so the commands, mappings, menus etc. will be available only for **delphi** files. The necessary _autocmd_-s are defined by the plugin.
The filetype **delphi** is defined also by the plugin, so

    ...{ 'for': ['delphi'...

makes no sense, I think. You should ask the developer of  [vim-plug](https://github.com/junegunn/vim-plug)

However

    ...{ 'for': ['pascal'] }

might work, but it won't bring too much benefit.

If doubt, You can examine the output of 

    vim --startuptime 

and memory consumtion. 
Let me know, if you find it is usefull!
