### ISSUE TITLE
How can I change the indent with space by default

### ISSUE THREAD

**Issue by caryyu** [mattia72/vim-delphi#6]
Currently, the syntax check will forcibly tell the code indents are space-based not tab, can I choose not to have to use the tabs for the indents thanks.

**Comment by caryyu** [comment]
Found some settings here: https://github.com/mattia72/vim-delphi/blob/master/doc/delphi.txt#L75-L82, but still no idea how to change the new line automating with the space indentation by default

**Comment by caryyu** [comment]
I saw that here's the replacement, but I have no idea how to edit this to fit my demand: https://github.com/mattia72/vim-delphi/blob/ccddb29aea1281fdf4551d5ebe3df1942afd92b8/plugin/delphi.vim#L316

**Comment by caryyu** [comment]
Got the solution by setting with `set noexpandtab`  but the weird thing is that I can't set in the global config, it can only take effect after `:so $MYVIMRC` being reloaded, anyhow, it can solve the problem for now.

**Comment by mattia72** [comment]
I usually work with sessions, or you could put such settings in a separate file which you can load before you edit a delphi file:
`so my-delphi-settings.vim `

You can put it as autocmd in your vimrc:
`autocmd FileType delphi so my-delphi-settings.vim<C-R><C-W>`

**Comment by caryyu** [comment]
@mattia72 Thanks, will give a try.
